from building import *
import os

cwd = GetCurrentDir()
CPPPATH = []
src = []
if GetDepend(['BSP_USING_APP_FONTS']):
    CPPPATH.append(cwd)

group = DefineGroup('Font library', src, depend=['BSP_USING_APP_FONTS'], CPPPATH=CPPPATH)

Return('group')