from building import *
import os

cwd = GetCurrentDir()
src = []
CPPPATH = []
if GetDepend(['BSP_USING_APP_ARDUINO']):
    src.append('Arduino.cpp')
    CPPPATH.append(cwd)    

group = DefineGroup('Arduino library', src, depend=['BSP_USING_APP_ARDUINO'], CPPPATH=CPPPATH)

Return('group')